# Generated by Django 2.2.7 on 2019-12-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=30)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_number', models.CharField(max_length=16)),
                ('host_name', models.CharField(max_length=30)),
                ('host_email', models.EmailField(max_length=254)),
                ('host_number', models.CharField(max_length=16)),
                ('check_in', models.TimeField(auto_now_add=True)),
                ('check_out', models.TimeField(auto_now=True)),
            ],
        ),
    ]
